OUT_DIR: "/home/bbessell/STRomboli/results/"
DATA_DIR: "/scratch/remills_root/remills99/bbessell/long_reads"
SNP_DIR: "/scratch/remills_root/remills99/bbessell/1kG_SNP_Panel/"
SNP_TR_PANEL_DIR: "/scratch/remills_root/remills99/bbessell/EnsembleTR_SNP_TR_Panel/"
REF_FASTA: "./genomes/GRCh38_latest_genomic.fna.gz"
CHROMOSOMES: "chr21"
BEAGLE_JAR_PATH: "/home/bbessell/STRomboli/software/beagle.22Jul22.46e.jar"
IGNORE_SAMPLES: "HG00513, HG00514"