OUT_DIR: "/home/bbessell/STRomboli/results/"
DATA_DIR: "/scratch/remills_root/remills99/bbessell/assemblies/assemblies.alignment.1025"
SHORT_READS_DIR: "/scratch/remills_root/remills1/shared_data/AssemblyGenomesForSTR/"
SNP_DIR: "/scratch/remills_root/remills99/bbessell/1kG_SNP_Panel/"
SNP_TR_PANEL_DIR: "/scratch/remills_root/remills99/bbessell/EnsembleTR_SNP_TR_Panel/"
REF_FASTA: "/scratch/remills_root/remills99/bbessell/genomes/GRCh38_latest_genomic.fna.gz"
CHROMOSOMES: "chr21"
#CHROMOSOMES: "chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15,chr 16, chr17, chr18, chr19, chr20, chr21, chr22"
BEAGLE_JAR_PATH: "/home/bbessell/STRomboli/software/beagle.22Jul22.46e.jar"
STRAGLR_PATH: "/home/bbessell/STRomboli/software/straglr/straglr.py"
IGNORE_SAMPLES: "HG00513, HG00514"
VAMOS_PATH: "/home/bbessell/software/vamos-v1.2.0_x64-linux"
EMOTIFS: "/home/bbessell/refs/vntr_region_motifs.e.bed"